"""add project mount metadata

Revision ID: dc06b3e5d9c5
Revises: c7900166fbca
Create Date: 2026-04-01 20:07:13.137184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc06b3e5d9c5'
down_revision: Union[str, Sequence[str], None] = 'c7900166fbca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('mount_name', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('mount_access_mode', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'mount_access_mode')
    op.drop_column('projects', 'mount_name')
    # ### end Alembic commands ###
